// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "string",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get./products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "404 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ProductResponse": {
      "properties": {
        "id": {
          "title": "ProductResponse.id",
          "type": "number"
        },
        "title": {
          "title": "ProductResponse.title",
          "type": "string"
        },
        "price": {
          "title": "ProductResponse.price",
          "type": "number"
        },
        "description": {
          "title": "ProductResponse.description",
          "type": "string"
        },
        "category": {
          "title": "ProductResponse.category",
          "type": "string"
        },
        "image": {
          "title": "ProductResponse.image",
          "type": "string"
        },
        "rating": {
          "properties": {
            "rate": {
              "title": "ProductResponse.rating.rate",
              "type": "number"
            },
            "count": {
              "title": "ProductResponse.rating.count",
              "type": "number"
            }
          },
          "required": [
            "rate",
            "count"
          ],
          "additionalProperties": false,
          "title": "ProductResponse.rating",
          "type": "object"
        }
      },
      "required": [
        "id",
        "title",
        "price",
        "description",
        "category",
        "image",
        "rating"
      ],
      "additionalProperties": false,
      "title": "ProductResponse",
      "type": "object"
    },
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "image": {
          "title": "Product.image",
          "type": "string"
        },
        "count": {
          "title": "Product.count",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "price",
        "description",
        "image",
        "count"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    },
    "ErrorResponse": {
      "properties": {
        "message": {
          "title": "ErrorResponse.message",
          "type": "string"
        },
        "statusCode": {
          "title": "ErrorResponse.statusCode",
          "type": "number"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https"
  ]
};