// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "string",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Products"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      },
      "post": {
        "summary": "createProduct",
        "description": "",
        "operationId": "createProduct.post./products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "description": "Body required in the request",
            "required": true,
            "schema": {
              "$ref": "#/definitions/ProductBody"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "400 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get./products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "schema": {
              "$ref": "#/definitions/Product"
            }
          },
          "404": {
            "description": "404 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          },
          "500": {
            "description": "500 response",
            "schema": {
              "$ref": "#/definitions/ErrorResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "image": {
          "title": "Product.image",
          "type": "string"
        },
        "count": {
          "title": "Product.count",
          "type": "number"
        }
      },
      "required": [
        "id",
        "title",
        "price",
        "description",
        "image",
        "count"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "ProductBody": {
      "properties": {
        "title": {
          "title": "ProductBody.title",
          "type": "string"
        },
        "price": {
          "title": "ProductBody.price",
          "type": "number"
        },
        "description": {
          "title": "ProductBody.description",
          "type": "string"
        },
        "image": {
          "title": "ProductBody.image",
          "type": "string"
        },
        "count": {
          "title": "ProductBody.count",
          "type": "number"
        }
      },
      "required": [
        "title",
        "price",
        "description",
        "image",
        "count"
      ],
      "additionalProperties": false,
      "title": "ProductBody",
      "type": "object"
    },
    "Products": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "Products.[]"
      },
      "title": "Products.[]",
      "type": "array"
    },
    "ErrorResponse": {
      "properties": {
        "message": {
          "title": "ErrorResponse.message",
          "type": "string"
        },
        "statusCode": {
          "title": "ErrorResponse.statusCode",
          "type": "number"
        }
      },
      "required": [
        "message"
      ],
      "additionalProperties": false,
      "title": "ErrorResponse",
      "type": "object"
    }
  },
  "securityDefinitions": {},
  "basePath": "/dev",
  "schemes": [
    "https"
  ]
};